# Generated by Django 2.1.2 on 2018-10-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Txer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='Nah', max_length=40),
        ),
    ]
