# Generated by Django 2.1.2 on 2018-11-07 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Txer', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='Not Set', max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('students', models.ManyToManyField(related_name='Class_Students', to='Txer.UserProfile')),
                ('teacher', models.ManyToManyField(related_name='Class_Teacher', to='Txer.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('students', models.ManyToManyField(related_name='School_Students', to='Txer.UserProfile')),
                ('teachers', models.ManyToManyField(related_name='School_Teachers', to='Txer.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('MinStudent', models.IntegerField(default=0)),
                ('MaxStudent', models.IntegerField(default=10000)),
                ('Joinable', models.BooleanField(default=False)),
                ('Desc', models.CharField(blank=True, max_length=500, null=True)),
                ('Start_Time', models.DateTimeField(blank=True, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('tutorial_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('tutorial_material', models.FileField(blank=True, null=True, upload_to='')),
                ('archived', models.BooleanField(default=False)),
                ('attended_students', models.ManyToManyField(related_name='Attended_students', to='Txer.UserProfile')),
                ('classes', models.ManyToManyField(related_name='Tutorial_Class', to='Tutorials.Classes')),
                ('students', models.ManyToManyField(related_name='Tutorial_Students', to='Txer.UserProfile')),
                ('teacher', models.ManyToManyField(related_name='Tutorial_Teacher', to='Txer.UserProfile')),
            ],
        ),
    ]
