# Generated by Django 2.1.2 on 2018-12-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Txer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='Not Set', max_length=100)),
                ('class_id', models.CharField(blank=True, max_length=100, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('uuid', models.CharField(default='BP9WFS', max_length=6, primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(default='01H90W', max_length=6)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('students', models.ManyToManyField(related_name='School_Students', to='Txer.UserProfile')),
                ('teachers', models.ManyToManyField(related_name='School_Teachers', to='Txer.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('MinStudent', models.IntegerField(default=0)),
                ('MaxStudent', models.IntegerField(default=10000)),
                ('Joinable', models.BooleanField(default=False)),
                ('Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Start_Time', models.DateTimeField(blank=True, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('Location', models.CharField(default='Not Set', max_length=100)),
                ('tutorial_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tutorial_material', models.FileField(blank=True, null=True, upload_to='')),
                ('archived', models.BooleanField(default=False)),
                ('repeat_weekly', models.BooleanField(blank=True, null=True)),
                ('repeat_daily', models.BooleanField(blank=True, null=True)),
                ('repeat_monday', models.BooleanField(blank=True, null=True)),
                ('repeat_tuesday', models.BooleanField(blank=True, null=True)),
                ('repeat_wednesday', models.BooleanField(blank=True, null=True)),
                ('repeat_thursday', models.BooleanField(blank=True, null=True)),
                ('repeat_friday', models.BooleanField(blank=True, null=True)),
                ('repeat_saturday', models.BooleanField(blank=True, null=True)),
                ('repeat_sunday', models.BooleanField(blank=True, null=True)),
                ('repeat_start_date', models.DateField(blank=True, null=True)),
                ('repeat_end_date', models.DateField(blank=True, null=True)),
                ('attended_students', models.ManyToManyField(related_name='Attended_students', to='Txer.UserProfile')),
                ('classes', models.ManyToManyField(related_name='Tutorial_Class', to='Tutorials.Classes')),
                ('students', models.ManyToManyField(related_name='Tutorial_Students', to='Txer.UserProfile')),
                ('teacher', models.ManyToManyField(related_name='Tutorial_Teacher', to='Txer.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='school',
            field=models.ManyToManyField(related_name='Classes_School', to='Tutorials.School'),
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='Class_Students', to='Txer.UserProfile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ManyToManyField(related_name='Class_Teacher', to='Txer.UserProfile'),
        ),
    ]
