# Generated by Django 2.1.2 on 2018-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
