# Generated by Django 2.1.2 on 2018-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0002_classes_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='RHIIX4', max_length=6, primary_key=True, serialize=False),
        ),
    ]
