# Generated by Django 2.1.2 on 2018-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0003_auto_20181107_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='B2ZX3N', max_length=6, primary_key=True, serialize=False),
        ),
    ]
