# Generated by Django 2.1.2 on 2018-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0004_auto_20181107_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(default='YRN0XN', max_length=6),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='IO3EMO', max_length=6, primary_key=True, serialize=False),
        ),
    ]
