# Generated by Django 2.1.2 on 2018-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0005_auto_20181111_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='school',
            field=models.ManyToManyField(related_name='Classes_School', to='Tutorials.School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(default='IAQNGS', max_length=6),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='1NVWXB', max_length=6, primary_key=True, serialize=False),
        ),
    ]
